### ISSUE TITLE
PDFs Request

### ISSUE THREAD

**Issue by spuder** [aggressiveHiker/rhce9-docs-ansible#1]
Thanks for making this collection. 

On the RHCE they provide PDFs. Would it be possible to consolidate these into a PDF instead of having to spin up a web server?

**Comment by aggressiveHiker** [comment]
Hmm... When I took the RHCE last May, we just got a locally hosted web server with the link navigation on the left. Has that since changed, and they're putting out PDFs now? Or are PDFs supplied in addition to the web server?

**Comment by spuder** [comment]
They provided both if I recall correctly.

Since #2 got merged I think the nginx docker container is a simpler solution.
